### ISSUE TITLE
Password encryption

### ISSUE THREAD

**Issue by UNOMAHANLYON** [Hungover-Software/Night-Out#17]
use Bcrypt gem file to encrypt user passwords for security.

**Comment by BParajuli** [comment]
It seems as though there is password encryption on the signin page.  However, more testing needs to be done to completely be sure.

**Comment by BParajuli** [comment]
Password encryption is implemented on the user model, however we do not know if it is being called(handled) correctly by the controller.  More testing is needed.

**Comment by BParajuli** [comment]
We correctly implemented has_secure_password to handle the validation and security of the user's sensitive information.

**Comment by BParajuli** [comment]
Password is now correctly entered into the database without being in plain text.  Password_digest is stored which is the user's encrypted password.
