### ISSUE TITLE
Add Create Account Page

### ISSUE THREAD

**Issue by gemmabuilds** [Hungover-Software/Night-Out#7]
# User Story
As a social butterfly, I want to be able to create an account, so that I can create and join events with friends.

## Acceptance Criteria
Create a rough page for creating an account and add it to the routes.

## Technical Notes
Use `rails generate controller` to make files for a new controller and page.

**Comment by gemmabuilds** [comment]
Completed work in commit 64d855db0e7a708e667a0bd59d46e16f6f53be0e

**Comment by BParajuli** [comment]
Looks good ready to deploy to Heroku.
